import 'package:flutter/material.dart';

const String iconFont = 'CupertinoIcons';
const String iconFontPackage = 'cupertino_icons';

const Map<String, IconData> cupertinoIcons = {
  'left_chevron': const IconData(0xf3d2,
      fontFamily: iconFont,
      fontPackage: iconFontPackage,
      matchTextDirection: true),
  'right_chevron': const IconData(0xf3d3,
      fontFamily: iconFont,
      fontPackage: iconFontPackage,
      matchTextDirection: true),
  'share': const IconData(0xf4ca,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'share_solid': const IconData(0xf4cb,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'book': const IconData(0xf3e7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'book_solid': const IconData(0xf3e8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bookmark': const IconData(0xf3e9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bookmark_solid': const IconData(0xf3ea,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'info': const IconData(0xf44c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'reply': const IconData(0xf4c6,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'conversation_bubble': const IconData(0xf3fb,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'profile_circled': const IconData(0xf419,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'plus_circled': const IconData(0xf48a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'minus_circled': const IconData(0xf463,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'flag': const IconData(0xf42c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'search': const IconData(0xf4a5,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'check_mark': const IconData(0xf3fd,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'check_mark_circled': const IconData(0xf3fe,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'check_mark_circled_solid': const IconData(0xf3ff,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'circle': const IconData(0xf401,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'circle_filled': const IconData(0xf400,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'back': const IconData(0xf3cf,
      fontFamily: iconFont,
      fontPackage: iconFontPackage,
      matchTextDirection: true),
  'forward': const IconData(0xf3d1,
      fontFamily: iconFont,
      fontPackage: iconFontPackage,
      matchTextDirection: true),
  'home': const IconData(0xf447,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'shopping_cart': const IconData(0xf3f7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'ellipsis': const IconData(0xf46a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'phone': const IconData(0xf4b8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'phone_solid': const IconData(0xf4b9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'down_arrow': const IconData(0xf35d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'up_arrow': const IconData(0xf366,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'battery_charging': const IconData(0xf111,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'battery_empty': const IconData(0xf112,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'battery_full': const IconData(0xf113,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'battery_75_percent': const IconData(0xf114,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'battery_25_percent': const IconData(0xf115,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bluetooth': const IconData(0xf116,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'restart': const IconData(0xf21c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'reply_all': const IconData(0xf21d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'reply_thick_solid': const IconData(0xf21e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'share_up': const IconData(0xf220,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'shuffle': const IconData(0xf4a9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'shuffle_medium': const IconData(0xf4a8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'shuffle_thick': const IconData(0xf221,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'photo_camera': const IconData(0xf3f5,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'photo_camera_solid': const IconData(0xf3f6,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'video_camera': const IconData(0xf4cc,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'video_camera_solid': const IconData(0xf4cd,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'switch_camera': const IconData(0xf49e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'switch_camera_solid': const IconData(0xf49f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'collections': const IconData(0xf3c9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'collections_solid': const IconData(0xf3ca,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'folder': const IconData(0xf434,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'folder_solid': const IconData(0xf435,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'folder_open': const IconData(0xf38a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'delete': const IconData(0xf4c4,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'delete_solid': const IconData(0xf4c5,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'delete_simple': const IconData(0xf37f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'pen': const IconData(0xf2bf,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'pencil': const IconData(0xf37e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'create': const IconData(0xf417,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'create_solid': const IconData(0xf417,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh': const IconData(0xf49a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh_circled': const IconData(0xf49b,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh_circled_solid': const IconData(0xf49c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh_thin': const IconData(0xf49d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh_thick': const IconData(0xf3a8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'refresh_bold': const IconData(0xf21c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clear_thick': const IconData(0xf2d7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clear_thick_circled': const IconData(0xf36e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clear': const IconData(0xf404,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clear_circled': const IconData(0xf405,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clear_circled_solid': const IconData(0xf406,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'add': const IconData(0xf489,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'add_circled': const IconData(0xf48a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'add_circled_solid': const IconData(0xf48b,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'gear': const IconData(0xf43c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'gear_solid': const IconData(0xf43d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'gear_big': const IconData(0xf2f7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'settings': const IconData(0xf411,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'settings_solid': const IconData(0xf412,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'music_note': const IconData(0xf46b,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'double_music_note': const IconData(0xf46c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'play_arrow': const IconData(0xf487,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'play_arrow_solid': const IconData(0xf488,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'pause': const IconData(0xf477,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'pause_solid': const IconData(0xf478,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'loop': const IconData(0xf449,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'loop_thick': const IconData(0xf44a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'volume_down': const IconData(0xf3b7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'volume_mute': const IconData(0xf3b8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'volume_off': const IconData(0xf3b9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'volume_up': const IconData(0xf3ba,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'fullscreen': const IconData(0xf386,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'fullscreen_exit': const IconData(0xf37d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'mic_off': const IconData(0xf45f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'mic': const IconData(0xf460,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'mic_solid': const IconData(0xf461,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clock': const IconData(0xf4be,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'clock_solid': const IconData(0xf4bf,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'time': const IconData(0xf402,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'time_solid': const IconData(0xf403,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'padlock': const IconData(0xf4c8,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'padlock_solid': const IconData(0xf4c9,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'eye': const IconData(0xf424,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'eye_solid': const IconData(0xf425,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'person': const IconData(0xf47d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'person_solid': const IconData(0xf47e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'person_add': const IconData(0xf47f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'person_add_solid': const IconData(0xf480,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'group': const IconData(0xf47b,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'group_solid': const IconData(0xf47c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'mail': const IconData(0xf422,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'mail_solid': const IconData(0xf423,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'location': const IconData(0xf455,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'location_solid': const IconData(0xf456,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'tag': const IconData(0xf48c,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'tag_solid': const IconData(0xf48d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'tags': const IconData(0xf48e,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'tags_solid': const IconData(0xf48f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bus': const IconData(0xf36d,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'car': const IconData(0xf36f,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'car_detailed': const IconData(0xf2c1,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'train_style_one': const IconData(0xf3af,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'train_style_two': const IconData(0xf3b4,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'paw': const IconData(0xf479,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'paw_solid': const IconData(0xf47a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'game_controller': const IconData(0xf43a,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'game_controller_solid': const IconData(0xf43b,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'lab_flask': const IconData(0xf430,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'lab_flask_solid': const IconData(0xf431,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'heart': const IconData(0xf442,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'heart_solid': const IconData(0xf443,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bell': const IconData(0xf3e1,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'bell_solid': const IconData(0xf3e2,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'news': const IconData(0xf471,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'news_solid': const IconData(0xf472,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'brightness': const IconData(0xf4B6,
      fontFamily: iconFont, fontPackage: iconFontPackage),
  'brightness_solid': const IconData(0xf4B7,
      fontFamily: iconFont, fontPackage: iconFontPackage),
};
