/// Flutter icons FrinoIcons
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ignore_for_file: unused_element

import 'package:flutter/widgets.dart';

const _kFontFam = 'LineAwesomeIcons';
const _kFontPackage = 'flutter_iconpicker';

const Map<String, IconData> lineAwesomeIcons = {};
