/// Flutter icons FrinoIcons
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ignore_for_file: unused_element

import 'package:flutter_iconpicker/Models/icon_picker_icon.dart';

const _kFontFam = 'LineAwesomeIcons';
const _kFontPackage = 'flutter_iconpicker';

const Map<String, IconPickerIcon> lineAwesomeIcons = {};
